name: vetclinic_app
description: "App móvil para clientes de clínica veterinaria — seguridad OWASP MASVS L2+R"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ── UI & Navigation ──────────────────────────────────────────
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10

  # ── State Management ─────────────────────────────────────────
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.7

  # ── Network ──────────────────────────────────────────────────
  dio: ^5.4.3

  # ── Security: Storage (MASVS-STORAGE-1) ──────────────────────
  flutter_secure_storage: ^9.0.0

  # ── Security: Auth biométrica (MASVS-AUTH-2) ─────────────────
  local_auth: ^2.2.0

  # ── Security: RASP (MASVS-RESILIENCE-1) ──────────────────────
  freerasp: ^6.4.0

  # ── Security: Anti-hardcoding secrets (M1) ───────────────────
  envied: ^0.5.3

  # ── Utilities ────────────────────────────────────────────────
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  envied_generator: ^0.5.3
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
